name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: | 
        docker image build -t mjlb/docker-graphql:0.0.3 .
        docker image build -t mjlb/docker-graphql:latest .
    - name: Push Docker Image
      run: |
        docker image push mjlb/docker-graphql:0.0.3
        docker image push mjlb/docker-graphql:latest
